version: "3.9"

services:
  bot:
    build: .
    container_name: week-billioner-bot
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: always
